# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "gubscruz"
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gubscruz/prova-final-zambom:${{ github.sha }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ubuntu"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
          docker network inspect rede-pf >/dev/null 2>&1 || docker network create rede-pf
          docker stop container-pf || true
          docker rm --force container-pf || true
          docker run -d -p 8080:8080 --network=rede-pf --name container-pf gubscruz/prova-final-zambom:${{ github.sha }}
